# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15HmZq6shECVkere2IfskJD0kEIGQOVlh
"""

#include<stdio.h>


int main(){
    int n= 10, a = 0, b =  1,next;
    for(int 10;i<n;i++);{
    printf("%d",a);
    next = a+b;
    a=b;
    b=next;
    }
    return 0;






    }

def fibonacci(n):
    a, b = 0, 1
    print("Fibonacci sequence:")
    for _ in range(n):
        print(a)
        next_val = a + b
        a = b
        b = next_val

# Call the function to generate the first 10 Fibonacci numbers
fibonacci(10)