# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15HmZq6shECVkere2IfskJD0kEIGQOVlh
"""

#include<stdio.h>


int main(){
    int n= 10, a = 0, b =  1,next;
    for(int 10;i<n;i++);{
    printf("%d",a);
    next = a+b;
    a=b;
    b=next;
    }
    return 0;






    }

def fibonacci(n):
    a, b = 0, 1
    print("Fibonacci sequence:")
    for _ in range(n):
        print(a)
        next_val = a + b
        a = b
        b = next_val

# Call the function to generate the first 10 Fibonacci numbers
fibonacci(10)

#include<stdio.h>
#include<string.h>

int isPalindrome(char str[]){
    int len = strlen(str);
    for (int i=0;i<len;i++){
        if(str[i]!=str[len-i]){
            return 0;
        }
    }

def is_palindrome(s):
    # Remove spaces and convert to lowercase for case-insensitive check
    s = s.replace(" ", "").lower()
    return s == s[::-1]

# Demonstrate the function
print(f"'madam' is a palindrome: {is_palindrome('madam')}")
print(f"'hello' is a palindrome: {is_palindrome('hello')}")
print(f"'Racecar' is a palindrome: {is_palindrome('Racecar')}")